title: Hello, world! I'm Pushkara Sharma
description: > # this means to ignore newlines until "baseurl:"
  I am a final year undergrad , i like to explore technologies and 
  currently i am dating all technologies and will settle on one 
  someday thats what i think
#permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://PushkaraSharma.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Pushkara Sharma # add your name
author-img: pushkara.jpg # add your photo
about-author: I am a chef of code and always hungry to keep learning. # add description
social-twitter: pushkarasays # add your Twitter handle
social-facebook:  # add your Facebook handle
social-github: PushkaraSharma # add your Github handle
social-linkedin: pushkara-sharma-bb2007182 # add your Linkedin handle
social-email: pushkarasharma11@gmail.com # add your Email address

# Disqus
discus-identifier: pushkarasharma # add your discus identifier

# Tracker
#analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 4
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
